# Installations

# Imports

In [1]:
import io
import os
%matplotlib inline
import matplotlib.pyplot as plt

# data management
import xarray as xr
import numpy as np
import pandas as pd

# Azure Connectivity
import getpass
import azure.storage.blob
from azure.storage.blob import BlobClient

# utilities
import time
import urllib.parse
from random import randint


### Function to download a specified file

In [2]:
def download_file(sas_url, filename, overwrite_local_file):
    """
    Downloads the specified file from Azure blob storage
    If asked to not overwrite, then first checks if the file is available locally and does not download again in that case.
    - sas_url   : url complete with sas token
    - filename  : name of the downloaded file
    - overwrite_local_file : if True, will overwrite, else, if already available locally, will not download again.
    Returns:  None
    """
    if overwrite_local_file or not (os.path.isfile(filename)):        
        blob_client = BlobClient.from_blob_url(sas_url)
        with open(filename, "wb") as my_blob:
            download_stream = blob_client.download_blob()
            my_blob.write(download_stream.readall())

                  

In [12]:
def calculate_average_for_region(ds_for_region):
    """
    Takes in an xarray dataset that represents a region, over a specific time dimension 
    and reduces all of the cells in the region, for each time period, to a single 
    average value. The individual lat, lon grids for each time period become 
    a single average value.
    Input Parameters:
    - ds_for_region  : xarray dataframe 
    Returns:  The xarray dataset 'ds_for_region' that contains the average of the values across the entire region. 
    """
    
    num_of_lats = len(ds_for_region.coords['lat'].values)
    num_of_lons = len(ds_for_region.coords['lon'].values)
    
    total_cells_in_region = num_of_lats * num_of_lons
    
    return ds_for_region.sum(dim='lat').sum(dim='lon').pipe(lambda x: x / total_cells_in_region)




In [13]:
def convert_kelvin_to_celsius(temp: float) -> float:
    """
    Converts Kelvin temperature to Celcius
    Input Parameters:
    - temp  : float
    Returns: float celsius value 
    """
    return temp - 273.15

In [14]:
def convert_kelvin_to_fahrenheit(temp: float) -> float:
    """
    Converts Kelvin temperature to Fahrenheit
    Input Parameters:
    - temp  : float
    Returns: float fahrenheit value 
    """
    return (temp - 273.15)*(9/5) + 32

In [15]:
def get_region_and_generate_average(ds, start_lat: float, end_lat: float, start_lon: float, end_lon: float, outputUnits: str = 'K'):
    """
    Takes in an xarray dataset that represents a region, over a specific time dimension 
    and reduces all of the cells in the region, for each time period, to a single 
    average value. The individual lat, lon grids for each time period become 
    a single average value.
    Input Parameters:
    - ds  : xarray dataframe 
    - start_lat  : float starting latitude of region
    - end_lat  : float ending latitude of region
    - start_lon  : float starting lonitude of region
    - end_lon  : float endinging lonitude of region
    - outputUnits  : string desired output units
    Returns:  The xarray dataset 'ds_avg_region' that contains the average of the values across the entire region converted to desired units. 
    """
    
    ACCEPTED_UNITS = ["C", "F", "K"]
    desiredUnits = outputUnits.upper()
    
    # Baseline Checks to make sure Inputs are reasonable
    if start_lat >= end_lat:
        raise Exception("CoordinateException: start_lat must be smaller than end_lat")
    if start_lon >= end_lon:
        raise Exception("CoordinateException: start_lon must be smaller than end_lon")
    
    if desiredUnits in ACCEPTED_UNITS:
        # Slice the region of interest out of your Dataset
        ds_avg_region = calculate_average_for_region(ds.sel(lat=slice(start_lat, end_lat), lon=slice(start_lon, end_lon)))
        
        # Dataset is as small as possible so now it is time for unit conversion
        if desiredUnits == ACCEPTED_UNITS[0]:
            ds_avg_region = ds_avg_region.map(convert_kelvin_to_celsius)
        elif desiredUnits == ACCEPTED_UNITS[1] :
            ds_avg_region = ds_avg_region.map(convert_kelvin_to_fahrenheit)
    else:
        raise Exception("InvalidOutputUnitsException: must be one of: " + ", ".join(ACCEPTED_UNITS))
    
    return ds_avg_region
       

## Calculating Averages for a Particular Region

In [7]:
average_ds_filename = 'Avg_temp_max_CMIP6__30_yrs__1950_to_1979.nc'
max_temp_ds_filename = '10_year_max_temp__Rgn_1__2020_to_2029__CMIP6_ssp245.nc'

average_ds = xr.open_dataset(average_ds_filename)
temps_ds = xr.open_dataset(max_temp_ds_filename)



In [8]:
average_ds

<xarray.Dataset>
Dimensions:    (lat: 600, lon: 1440, day: 365)
Coordinates:
  * lat        (lat) float64 -59.88 -59.62 -59.38 -59.12 ... 89.38 89.62 89.88
  * lon        (lon) float64 0.125 0.375 0.625 0.875 ... 359.1 359.4 359.6 359.9
  * day        (day) int64 1 2 3 4 5 6 7 8 9 ... 358 359 360 361 362 363 364 365
Data variables:
    tasmaxavg  (day, lat, lon) float32 ...
    tasmaxrec  (day, lat, lon) float32 ...
Attributes:
    Dataset:           Average temperature CMIP6
    About dataset:     A dataset with average and record temparatures, across...
    Original values:   tasmax
    Data variables:    ['tasmaxavg', 'tasmaxrec']
    Data description:  Average and record maximum temperature, based on tasmax
    Range:             30 years
    Start year:        1950
    End year:          1979
    Years processed:   30
    Store as:          Avg_temp_max_CMIP6__30_yrs__1950_to_1979.nc

In [11]:
temps_ds

<xarray.Dataset>
Dimensions:  (time: 3650, lat: 284, lon: 644)
Coordinates:
  * time     (time) object 2020-01-01 12:00:00 ... 2029-12-31 12:00:00
  * lat      (lat) float64 14.12 14.38 14.62 14.88 ... 84.12 84.38 84.62 84.88
  * lon      (lon) float64 190.1 190.4 190.6 190.9 ... 350.1 350.4 350.6 350.9
Data variables:
    tasmax   (time, lat, lon) float32 ...
Attributes: (12/16)
    Dataset:            10-year max temperature CMIP6 region_id: 1
    About dataset:      A dataset with 10-year temparatures (tasmax), for the...
    Data variables:     tasmax
    Data description:   10-year max temperature for the specified region
    Range:              10 years
    Start year:         2020
    ...                 ...
    region_bottom_lat:  14
    region_left_lon:    190
    region_right_lon:   350
    region_img_url:     https://github.com/techwork111/pa-datasets/blob/main/...
    Years processed:    2030
    Store as:           10_year_max_temp__Rgn_1__2020_to_2029__CMIP6_ssp245.nc

In [14]:
temp_2020_ds = temps_ds.sel(time='2020')

In [16]:
# Bounding Box For Seattle Region

start_lat = 47.25
end_lat = 48.12
start_lon = 237.68
end_lon = 238.44


In [16]:
average_ds = average_ds.sel(lat=slice(start_lat, end_lat), lon=slice(start_lon, end_lon))

In [17]:
temp_2020_ds = temp_2020_ds.sel(lat=slice(start_lat, end_lat), lon=slice(start_lon, end_lon))

In [20]:
average_ds

<xarray.Dataset>
Dimensions:    (lat: 3, lon: 3, day: 365)
Coordinates:
  * lat        (lat) float64 47.38 47.62 47.88
  * lon        (lon) float64 237.9 238.1 238.4
  * day        (day) int64 1 2 3 4 5 6 7 8 9 ... 358 359 360 361 362 363 364 365
Data variables:
    tasmaxavg  (day, lat, lon) float32 282.2 280.6 278.0 ... 281.7 280.8 277.9
    tasmaxrec  (day, lat, lon) float32 288.1 286.5 283.9 ... 286.3 285.5 282.6
Attributes:
    Dataset:           Average temperature CMIP6
    About dataset:     A dataset with average and record temparatures, across...
    Original values:   tasmax
    Data variables:    ['tasmaxavg', 'tasmaxrec']
    Data description:  Average and record maximum temperature, based on tasmax
    Range:             30 years
    Start year:        1950
    End year:          1979
    Years processed:   30
    Store as:          Avg_temp_max_CMIP6__30_yrs__1950_to_1979.nc

In [21]:
temp_2020_ds

<xarray.Dataset>
Dimensions:  (time: 365, lat: 3, lon: 3)
Coordinates:
  * time     (time) object 2020-01-01 12:00:00 ... 2020-12-31 12:00:00
  * lat      (lat) float64 47.38 47.62 47.88
  * lon      (lon) float64 237.9 238.1 238.4
Data variables:
    tasmax   (time, lat, lon) float32 283.5 281.8 279.1 ... 281.9 280.8 277.5
Attributes: (12/16)
    Dataset:            10-year max temperature CMIP6 region_id: 1
    About dataset:      A dataset with 10-year temparatures (tasmax), for the...
    Data variables:     tasmax
    Data description:   10-year max temperature for the specified region
    Range:              10 years
    Start year:         2020
    ...                 ...
    region_bottom_lat:  14
    region_left_lon:    190
    region_right_lon:   350
    region_img_url:     https://github.com/techwork111/pa-datasets/blob/main/...
    Years processed:    2030
    Store as:           10_year_max_temp__Rgn_1__2020_to_2029__CMIP6_ssp245.nc

### Swap time dimension with day dimension so comparisons will work correctly 

In [58]:
temp_2020_ds = temp_2020_ds.assign_coords(day=temp_2020_ds.time.dt.dayofyear)
temp_2020_ds = temp_2020_ds.swap_dims({"time": "day"})
temp_2020_ds

<xarray.Dataset>
Dimensions:  (day: 365, lat: 3, lon: 3)
Coordinates:
    time     (day) object 2020-01-01 12:00:00 ... 2020-12-31 12:00:00
  * lat      (lat) float64 47.38 47.62 47.88
  * lon      (lon) float64 237.9 238.1 238.4
  * day      (day) int64 1 2 3 4 5 6 7 8 9 ... 358 359 360 361 362 363 364 365
Data variables:
    tasmax   (day, lat, lon) float32 283.5 281.8 279.1 ... 281.9 280.8 277.5
Attributes: (12/16)
    Dataset:            10-year max temperature CMIP6 region_id: 1
    About dataset:      A dataset with 10-year temparatures (tasmax), for the...
    Data variables:     tasmax
    Data description:   10-year max temperature for the specified region
    Range:              10 years
    Start year:         2020
    ...                 ...
    region_bottom_lat:  14
    region_left_lon:    190
    region_right_lon:   350
    region_img_url:     https://github.com/techwork111/pa-datasets/blob/main/...
    Years processed:    2030
    Store as:           10_year_max_temp__Rgn_1__2020_to_2029__CMIP6_ssp245.nc

In [22]:
average_ds['tasmaxavg'][:]

<xarray.DataArray 'tasmaxavg' (day: 365, lat: 3, lon: 3)>
array([[[282.19, 280.56, 278.02],
        [282.27, 281.7 , 277.84],
        [282.12, 281.22, 278.23]],

       [[282.28, 280.67, 278.14],
        [282.41, 281.85, 278.01],
        [282.32, 281.43, 278.46]],

       ...,

       [[281.63, 280.02, 277.48],
        [281.78, 281.22, 277.37],
        [281.71, 280.83, 277.86]],

       [[281.76, 280.14, 277.62],
        [281.84, 281.29, 277.45],
        [281.71, 280.83, 277.86]]], dtype=float32)
Coordinates:
  * lat      (lat) float64 47.38 47.62 47.88
  * lon      (lon) float64 237.9 238.1 238.4
  * day      (day) int64 1 2 3 4 5 6 7 8 9 ... 358 359 360 361 362 363 364 365

In [60]:
temp_2020_ds['tasmax'][:]

<xarray.DataArray 'tasmax' (day: 365, lat: 3, lon: 3)>
array([[[283.50598, 281.75363, 279.08936],
        [283.6513 , 283.00104, 279.0739 ],
        [283.57446, 282.65125, 279.63983]],

       [[284.0698 , 282.44592, 279.90982],
        [284.35843, 283.7685 , 279.90308],
        [284.42462, 283.49503, 280.47916]],

       ...,

       [[281.23187, 279.23413, 276.32513],
        [281.60965, 280.67737, 276.46344],
        [281.76675, 280.52002, 277.17862]],

       [[281.21356, 279.27368, 276.42242],
        [281.6914 , 280.82977, 276.68826],
        [281.9479 , 280.78638, 277.5325 ]]], dtype=float32)
Coordinates:
    time     (day) object 2020-01-01 12:00:00 ... 2020-12-31 12:00:00
  * lat      (lat) float64 47.38 47.62 47.88
  * lon      (lon) float64 237.9 238.1 238.4
  * day      (day) int64 1 2 3 4 5 6 7 8 9 ... 358 359 360 361 362 363 364 365
Attributes:
    standard_name:  air_temperature
    long_name:      Daily Maximum Near-Surface Air Temperature
    units:          K
    comment:        maximum near-surface (usually, 2 meter) air temperature (...
    cell_methods:   area: mean time: maximum
    cell_measures:  area: areacella

In [80]:
temp_sub_ds = np.subtract(temp_2020_ds['tasmax'], average_ds['tasmaxavg'])
temp_sub_ds

<xarray.DataArray 'tasmax' (day: 365, lat: 3, lon: 3)>
array([[[ 1.315979  ,  1.193634  ,  1.0693665 ],
        [ 1.3813171 ,  1.3010254 ,  1.2339172 ],
        [ 1.4544678 ,  1.4312439 ,  1.4098206 ]],

       [[ 1.7897949 ,  1.7759094 ,  1.7698059 ],
        [ 1.9484253 ,  1.9184875 ,  1.8930664 ],
        [ 2.1046143 ,  2.065033  ,  2.019165  ]],

       [[ 1.9457092 ,  1.8702393 ,  1.8022156 ],
        [ 2.0661316 ,  1.9773254 ,  1.8942261 ],
        [ 2.18396   ,  2.089508  ,  1.990448  ]],

       ...,

       [[-1.0983276 , -1.2871094 , -1.4769287 ],
        [-1.0495605 , -1.2082825 , -1.3705444 ],
        [-0.9907532 , -1.1111755 , -1.2487793 ]],

       [[-0.39813232, -0.78585815, -1.1548767 ],
        [-0.17034912, -0.54263306, -0.9065552 ],
        [ 0.0567627 , -0.30996704, -0.68136597]],

       [[-0.54644775, -0.866333  , -1.1975708 ],
        [-0.14859009, -0.4602356 , -0.76174927],
        [ 0.23791504, -0.04360962, -0.32748413]]], dtype=float32)
Coordinates:
    time     (day) object 2020-01-01 12:00:00 ... 2020-12-31 12:00:00
  * lat      (lat) float64 47.38 47.62 47.88
  * lon      (lon) float64 237.9 238.1 238.4
  * day      (day) int64 1 2 3 4 5 6 7 8 9 ... 358 359 360 361 362 363 364 365
Attributes:
    standard_name:  air_temperature
    long_name:      Daily Maximum Near-Surface Air Temperature
    units:          K
    comment:        maximum near-surface (usually, 2 meter) air temperature (...
    cell_methods:   area: mean time: maximum
    cell_measures:  area: areacella

In [68]:
calculate_average_for_region(temp_sub_ds)

<xarray.DataArray 'tasmax' (day: 365)>
array([ 1.3100858e+00,  1.9204780e+00,  1.9799737e+00,  2.0627780e+00,
        3.2046001e+00,  4.2761059e+00,  6.9358659e-01, -1.3535699e+00,
       -3.4791903e+00, -2.3499858e+00, -7.0331490e-01, -8.6015493e-02,
        1.0585734e+00,  2.9227600e+00,  3.3738098e+00,  3.4156427e+00,
        3.7896085e+00,  3.4858873e+00,  3.4960327e+00,  4.2071400e+00,
        4.0311518e+00,  4.1503229e+00,  3.6128812e+00,  2.4926519e+00,
        1.8426751e+00,  1.2273526e+00,  2.9488628e+00,  3.3533223e+00,
        2.6409302e+00,  2.1707051e+00,  1.0705600e+00,  1.8286710e+00,
        1.3275994e+00, -8.8263620e-03,  2.3030260e-01, -7.1226335e-01,
       -1.4066535e+00,  5.5243596e-02,  1.3321432e+00,  1.7596537e+00,
        2.3360121e+00,  1.7204421e+00, -6.0760158e-01, -1.5533684e+00,
        1.7590569e+00,  1.7431641e+00,  1.7962443e+00,  1.8146667e+00,
        2.2066481e+00,  2.1484883e+00, -1.9951375e-01, -7.5908065e-01,
        7.6639473e-01,  7.4036324e-01, -3.5040283e+00, -2.3700933e+00,
       -1.2919685e+00, -1.6054891e+00, -7.1976727e-01,  3.4743583e-01,
        3.8209704e-01,  7.2415161e-01,  2.2955662e-01, -1.2277426e+00,
        1.0812514e+00,  3.8512471e+00,  4.1005249e+00,  3.3345845e+00,
       -7.5577801e-01, -1.6296997e+00, -1.5285848e+00, -5.0305855e-01,
        2.4389988e-01,  1.9620091e-01,  7.7006021e-03, -2.8669229e-01,
       -4.9524266e-01, -8.0544364e-01, -2.4651760e-01, -1.7440118e-01,
...
       -1.6581963e+00, -3.1925592e+00,  1.1497226e+00,  2.1873846e+00,
       -1.7471992e+00, -4.1717596e+00, -5.2241755e+00, -4.5796204e+00,
       -4.1693287e+00, -2.3835993e+00,  1.6100870e+00,  3.7964613e+00,
        5.3351407e+00,  5.3412375e+00,  1.6646219e+00,  3.1863911e+00,
        2.8274469e+00,  3.4253709e+00,  7.4094338e+00,  7.6321039e+00,
        3.3998005e+00,  8.4777832e-01,  2.5282049e+00,  1.6642693e+00,
       -1.9684550e+00, -1.4241842e+00,  8.0362953e-02, -1.8622844e-01,
       -3.5820857e-02,  3.6804879e-01,  1.6581895e+00,  1.1137865e+00,
       -9.4563127e-01,  1.3595039e+00,  1.1210666e+00,  8.4270561e-01,
       -4.0773857e-01,  1.8381348e+00,  6.8264431e-01, -1.0074056e+00,
       -2.0419651e-01, -5.8626300e-01,  2.6587491e+00, -2.4856534e+00,
       -3.6721938e+00, -5.1980796e+00, -8.7949867e+00, -5.1988354e+00,
       -7.6530290e-01, -1.3093126e+00,  1.9094510e+00,  2.0660536e+00,
       -1.3465711e-01,  1.1556498e+00,  1.5174255e+00,  8.0677289e-01,
        3.5444131e-01,  4.1020712e-01,  3.4491983e-01,  2.9466586e+00,
        3.8086751e+00,  4.1107922e+00,  1.5713400e+00, -3.1393093e-01,
       -1.9593879e+00, -1.8689270e+00,  1.7132772e+00,  2.1786668e+00,
        8.3361816e-01, -8.7534928e-01,  1.2356906e+00,  2.3717685e+00,
        1.4779562e+00, -1.4043172e-01, -1.2046068e+00, -5.4366386e-01,
       -4.5712280e-01], dtype=float32)
Coordinates:
    time     (day) object 2020-01-01 12:00:00 ... 2020-12-31 12:00:00
  * day      (day) int64 1 2 3 4 5 6 7 8 9 ... 358 359 360 361 362 363 364 365

## Simpler Difference Calcualtion 

In [78]:
average_simp_ds = calculate_average_for_region(average_ds)
temp_simp_ds = calculate_average_for_region(temp_2020_ds)

In [79]:
np.subtract(temp_simp_ds['tasmax'], average_simp_ds['tasmaxavg'])

<xarray.DataArray 'tasmax' (day: 365)>
array([ 1.3101196e+00,  1.9205017e+00,  1.9799805e+00,  2.0627747e+00,
        3.2045898e+00,  4.2760925e+00,  6.9360352e-01, -1.3536072e+00,
       -3.4792175e+00, -2.3500061e+00, -7.0330811e-01, -8.5998535e-02,
        1.0585938e+00,  2.9227905e+00,  3.3738098e+00,  3.4156189e+00,
        3.7896118e+00,  3.4858704e+00,  3.4960632e+00,  4.2071533e+00,
        4.0311279e+00,  4.1503296e+00,  3.6128845e+00,  2.4926453e+00,
        1.8426514e+00,  1.2273865e+00,  2.9488831e+00,  3.3533020e+00,
        2.6409302e+00,  2.1707153e+00,  1.0705566e+00,  1.8286438e+00,
        1.3276367e+00, -8.8195801e-03,  2.3025513e-01, -7.1228027e-01,
       -1.4066772e+00,  5.5236816e-02,  1.3321228e+00,  1.7596436e+00,
        2.3360291e+00,  1.7204590e+00, -6.0757446e-01, -1.5534058e+00,
        1.7590332e+00,  1.7431641e+00,  1.7962341e+00,  1.8146973e+00,
        2.2066650e+00,  2.1484985e+00, -1.9952393e-01, -7.5909424e-01,
        7.6638794e-01,  7.4035645e-01, -3.5040283e+00, -2.3701172e+00,
       -1.2919617e+00, -1.6054688e+00, -7.1975708e-01,  3.4744263e-01,
        3.8211060e-01,  7.2415161e-01,  2.2955322e-01, -1.2277527e+00,
        1.0812378e+00,  3.8512573e+00,  4.1005249e+00,  3.3345642e+00,
       -7.5576782e-01, -1.6297302e+00, -1.5285950e+00, -5.0311279e-01,
        2.4392700e-01,  1.9622803e-01,  7.7209473e-03, -2.8671265e-01,
       -4.9520874e-01, -8.0541992e-01, -2.4655151e-01, -1.7437744e-01,
...
       -1.6582031e+00, -3.1925659e+00,  1.1497498e+00,  2.1874084e+00,
       -1.7472229e+00, -4.1717224e+00, -5.2241821e+00, -4.5795898e+00,
       -4.1693420e+00, -2.3835754e+00,  1.6101074e+00,  3.7964478e+00,
        5.3351440e+00,  5.3412781e+00,  1.6646423e+00,  3.1863708e+00,
        2.8274536e+00,  3.4253540e+00,  7.4094238e+00,  7.6321106e+00,
        3.3998108e+00,  8.4777832e-01,  2.5281982e+00,  1.6642761e+00,
       -1.9684448e+00, -1.4241943e+00,  8.0352783e-02, -1.8624878e-01,
       -3.5827637e-02,  3.6807251e-01,  1.6581726e+00,  1.1138000e+00,
       -9.4561768e-01,  1.3595276e+00,  1.1210632e+00,  8.4265137e-01,
       -4.0774536e-01,  1.8381042e+00,  6.8261719e-01, -1.0074158e+00,
       -2.0422363e-01, -5.8627319e-01,  2.6587524e+00, -2.4856262e+00,
       -3.6722412e+00, -5.1980591e+00, -8.7949829e+00, -5.1988525e+00,
       -7.6531982e-01, -1.3092957e+00,  1.9094543e+00,  2.0660706e+00,
       -1.3467407e-01,  1.1556091e+00,  1.5174255e+00,  8.0676270e-01,
        3.5443115e-01,  4.1018677e-01,  3.4487915e-01,  2.9466553e+00,
        3.8086548e+00,  4.1107788e+00,  1.5713501e+00, -3.1393433e-01,
       -1.9594116e+00, -1.8689270e+00,  1.7132874e+00,  2.1786804e+00,
        8.3361816e-01, -8.7533569e-01,  1.2357178e+00,  2.3717346e+00,
        1.4779358e+00, -1.4044189e-01, -1.2046204e+00, -5.4370117e-01,
       -4.5712280e-01], dtype=float32)
Coordinates:
    time     (day) object 2020-01-01 12:00:00 ... 2020-12-31 12:00:00
  * day      (day) int64 1 2 3 4 5 6 7 8 9 ... 358 359 360 361 362 363 364 365

# Conclusion

Whether we are taking an average of the temperature difference of a region's pixels vs its historical average or getting the average temperature for an entire region and then subtracing it from the histroical average temperature for that entire region the results are the same.

### Using Updated extremes Files For Comparison

In [9]:
download_file("https://nasanex30analysis.blob.core.windows.net/cmip6/extremes_max/Ext_max_t__Rgn_1__2015__Abv_Avg_1_K_for_3_days__CMIP6_ssp245_Avg_yrs_1950_79.nc?sp=r&st=2021-10-21T04:11:44Z&se=2021-10-21T12:11:44Z&spr=https&sv=2020-08-04&sr=c&sig=5TSqNH6YUrPVApRjGKheLcYX8MTOj%2FC71cOxSBwGdT8%3D",
             "Ext_max_t__Rgn_1__2015__Abv_Avg_1_K_for_3_days__CMIP6_ssp245_Avg_yrs_1950_79.nc", True)





In [18]:
heat_extreme_ds = xr.open_dataset("Ext_max_t__Rgn_1__2015__Abv_Avg_1_K_for_3_days__CMIP6_ssp245_Avg_yrs_1950_79.nc")

heat_extreme_ds

<xarray.Dataset>
Dimensions:          (time: 365, lat: 284, lon: 644)
Coordinates:
  * time             (time) object 2015-01-01 12:00:00 ... 2015-12-31 12:00:00
  * lat              (lat) float64 14.12 14.38 14.62 14.88 ... 84.38 84.62 84.88
  * lon              (lon) float64 190.1 190.4 190.6 190.9 ... 350.4 350.6 350.9
Data variables:
    tasmax           (time, lat, lon) float32 ...
    above_threshold  (time, lat, lon) float32 ...
    extreme_yn       (time, lat, lon) float64 ...
Attributes: (12/24)
    Dataset:                                             1-year Extreme max T...
    About dataset:                                       1-year Extreme max T...
    Data variables:                                      tasmax, above_thresh...
    Data description:                                    max temperature; dif...
    Range:                                               1 year
    Analysis year:                                       2015
    ...                                                  ...
    region_bottom_lat:                                   14
    region_left_lon:                                     190
    region_right_lon:                                    350
    region_img_url:                                      https://github.com/t...
    Years processed:                                     1
    Store as:                                            Ext_max_t__Rgn_1__20...

In [19]:
heat_extreme_ds = heat_extreme_ds.sel(lat=slice(start_lat, end_lat), lon=slice(start_lon, end_lon))

heat_extreme_ds

<xarray.Dataset>
Dimensions:          (time: 365, lat: 3, lon: 3)
Coordinates:
  * time             (time) object 2015-01-01 12:00:00 ... 2015-12-31 12:00:00
  * lat              (lat) float64 47.38 47.62 47.88
  * lon              (lon) float64 237.9 238.1 238.4
Data variables:
    tasmax           (time, lat, lon) float32 ...
    above_threshold  (time, lat, lon) float32 ...
    extreme_yn       (time, lat, lon) float64 ...
Attributes: (12/24)
    Dataset:                                             1-year Extreme max T...
    About dataset:                                       1-year Extreme max T...
    Data variables:                                      tasmax, above_thresh...
    Data description:                                    max temperature; dif...
    Range:                                               1 year
    Analysis year:                                       2015
    ...                                                  ...
    region_bottom_lat:                                   14
    region_left_lon:                                     190
    region_right_lon:                                    350
    region_img_url:                                      https://github.com/t...
    Years processed:                                     1
    Store as:                                            Ext_max_t__Rgn_1__20...

In [20]:
heat_extreme_region_avg = calculate_average_for_region(heat_extreme_ds["above_threshold"])

heat_extreme_region_avg

<xarray.DataArray 'above_threshold' (time: 365)>
array([-2.53766894e+00, -1.04717338e+00, -7.90334046e-01, -3.22096419e+00,
       -3.49533415e+00, -3.24636507e+00, -4.28917122e+00, -2.62193131e+00,
        2.16175342e+00,  2.86064649e+00,  3.52739125e-01,  1.13486397e+00,
        8.57357442e-01,  2.11798763e+00,  2.06177092e+00, -1.29939103e+00,
       -5.08829737e+00, -5.70702791e+00, -2.90195727e+00, -1.09011841e+00,
       -9.87521708e-01, -5.56632137e+00, -8.09193611e+00, -8.74231339e+00,
       -1.01782398e+01, -4.94276619e+00, -3.05893970e+00,  7.72759318e-01,
        1.73737252e+00,  8.38958740e-01, -2.15939999e+00, -2.77380037e+00,
        1.08253312e+00,  1.72598267e+00,  3.04173446e+00,  2.54001200e-01,
       -3.39779663e+00, -3.24826384e+00, -5.83390999e+00, -4.07843709e-01,
        1.01453316e+00, -1.13945857e-01, -6.05596924e+00, -3.05259538e+00,
       -3.25734115e+00, -3.80698657e+00, -3.26756120e+00, -4.02148771e+00,
       -4.20714998e+00, -4.98966122e+00, -5.69075537e+00, -5.32357454e+00,
       -5.03699398e+00, -4.16362858e+00, -2.16184497e+00, -1.39239836e+00,
       -7.74291992e-01, -8.53291810e-01,  9.06056702e-01,  3.68326813e-01,
       -3.18040967e+00, -3.74955249e+00, -4.46752262e+00, -6.59658146e+00,
       -4.79710913e+00, -1.32721627e+00,  3.92222077e-01, -3.48297119e-01,
       -1.44094849e+00, -1.66066825e+00, -2.36487484e+00, -5.40276766e+00,
       -4.93826962e+00, -3.60765934e+00, -3.88948560e+00, -4.93629980e+00,
       -4.51764917e+00, -2.26900911e+00, -2.08988786e+00, -2.54794312e+00,
...
       -3.01288867e+00, -3.66784000e+00,  2.59955525e-01,  2.86293197e+00,
        1.57195032e+00, -3.75078321e+00, -2.77060270e+00, -1.54850936e+00,
       -2.12942171e+00, -1.87562728e+00, -2.69829631e-01,  1.24653792e+00,
        2.44007015e+00, -2.71389771e+00, -1.76559782e+00, -2.76723218e+00,
        1.21967912e+00,  1.45167029e+00, -4.71386051e+00, -3.91722608e+00,
       -3.38558292e+00, -3.28648543e+00, -2.49401522e+00, -2.60451603e+00,
       -2.81613827e+00, -2.79032397e+00, -1.64477205e+00,  2.38376200e-01,
       -6.16624616e-02, -3.04531515e-01,  8.77617747e-02, -9.77322042e-01,
       -1.59275985e+00, -2.19102311e+00, -2.70622754e+00, -4.49391699e+00,
        2.81945109e-01, -7.84237325e-01, -8.21794271e-01, -2.07553431e-02,
       -1.85216951e+00,  1.97775602e+00,  3.17192936e+00,  3.03942537e+00,
        2.38009310e+00,  1.01777816e+00,  2.06077075e+00,  2.72942781e+00,
        1.50231254e+00, -1.01771712e+00, -2.39236450e+00, -3.40478516e+00,
       -4.51233912e+00, -4.20812988e+00, -3.18201017e+00, -3.44007701e-01,
        3.72776628e+00,  4.91990834e-01, -1.74007845e+00, -1.79115808e+00,
       -1.40385604e+00, -8.33296061e-01, -1.58356047e+00, -2.56121159e+00,
       -5.21231747e+00, -5.62272120e+00, -6.22165585e+00, -5.36536980e+00,
       -5.93661499e+00, -5.52013826e+00, -1.88095093e+00,  1.85960561e-01,
        9.29256856e-01,  7.11449504e-01,  9.21207011e-01,  5.09101003e-02,
       -8.02917480e-02], dtype=float32)
Coordinates:
  * time     (time) object 2015-01-01 12:00:00 ... 2015-12-31 12:00:00